# Temporary status
- name: "🗯️ Waiting for feedback"
  color: "aadefa"
- name: "🔴 Blocked"
  color: "ff3f14"
  description: "Blocked by another issue or pull request"
- name: "🔒 After next release"
  color: "e8f274"
  description: "Will be done after the next release"

# Priority
- name: "🚨 Urgent"
  color: "d5232f"
- name: "💤 Low priority"
  color: "4285f4"

# Complexity
- name: "☣️ Hard to do"
  color: "7d0008"
- name: "🟩 Easy to do"
  color: "34cf43"

# VPN providers
- name: ":cloud: AirVPN"
  color: "cfe8d4"
- name: ":cloud: Cyberghost"
  color: "cfe8d4"
- name: ":cloud: HideMyAss"
  color: "cfe8d4"
- name: ":cloud: IPVanish"
  color: "cfe8d4"
- name: ":cloud: IVPN"
  color: "cfe8d4"
- name: ":cloud: ExpressVPN"
  color: "cfe8d4"
- name: ":cloud: FastestVPN"
  color: "cfe8d4"
- name: ":cloud: Mullvad"
  color: "cfe8d4"
- name: ":cloud: NordVPN"
  color: "cfe8d4"
- name: ":cloud: Perfect Privacy"
  color: "cfe8d4"
- name: ":cloud: PIA"
  color: "cfe8d4"
- name: ":cloud: Privado"
  color: "cfe8d4"
- name: ":cloud: PrivateVPN"
  color: "cfe8d4"
- name: ":cloud: ProtonVPN"
  color: "cfe8d4"
- name: ":cloud: PureVPN"
  color: "cfe8d4"
- name: ":cloud: SlickVPN"
  color: "cfe8d4"
- name: ":cloud: Surfshark"
  color: "cfe8d4"
- name: ":cloud: Torguard"
  color: "cfe8d4"
- name: ":cloud: VPNSecure.me"
  color: "cfe8d4"
- name: ":cloud: VPNUnlimited"
  color: "cfe8d4"
- name: ":cloud: Vyprvpn"
  color: "cfe8d4"
- name: ":cloud: WeVPN"
  color: "cfe8d4"
- name: ":cloud: Windscribe"
  color: "cfe8d4"

# Problem category
- name: "Config problem"
  color: "ffc7ea"
- name: "Openvpn"
  color: "ffc7ea"
- name: "Wireguard"
  color: "ffc7ea"
- name: "Unbound (DNS over TLS)"
  color: "ffc7ea"
- name: "Firewall"
  color: "ffc7ea"
- name: "Routing"
  color: "ffc7ea"
- name: "IPv6"
  color: "ffc7ea"
- name: "Port forwarding"
  color: "ffc7ea"
- name: "HTTP proxy"
  color: "ffc7ea"
- name: "Shadowsocks"
  color: "ffc7ea"
- name: "Healthcheck server"
  color: "ffc7ea"
- name: "Control server"
  color: "ffc7ea"
